### ISSUE TITLE
Object coloring

### ISSUE THREAD

**Issue by bsvipas** [michaelgmcd/vscode-language-babel#10]
@michaelgmcd Hi, I found problem in object coloring, it's hard to read text...

### BEFORE
<img width="328" alt="screenshot at oct 05 14-59-59" src="https://user-images.githubusercontent.com/30043375/31226282-2e14412e-a9de-11e7-8d83-1a69f29f68dd.png">

![image](https://user-images.githubusercontent.com/30043375/31226396-9ef804d4-a9de-11e7-8814-0316d677757f.png)

### AFTER
<img width="318" alt="screenshot at oct 05 15-00-25" src="https://user-images.githubusercontent.com/30043375/31226283-2e1556ea-a9de-11e7-96ca-f89577accc51.png">

![image](https://user-images.githubusercontent.com/30043375/31226367-883feb58-a9de-11e7-832e-e70d74c02b85.png)

As you can see `locationId` and `value` is yellow as string which is wrong they need to be white. By the way very awesome extension which is really good!!!

**Comment by michaelgmcd** [comment]
This is tough for me to address because it would be a pretty fundamental change to how language-babel represents keys in objects. They are in fact strings, so they are represented as such. If you were to write it this way (which is valid), would you expect them to still be white?
```
{
  "locationId": ...,
  "value": ...
}
```

Also, what tool are you using to view the token types (the larger screenshots)?

**Comment by bsvipas** [comment]
Right now I see JSON in white which is good. But I believe you're talking about JS objects.

```js
{
  "locationId": ..., // I expect it to be as a string (YELLOW)
}

{
  locationId: ..., // I expect it to be as object (WHITE)
}
```

Of course these colors depends on theme, but you get the idea. Objects are not in single/double quotes and they are identified as string which is not correct, BUT if they was in single/double quotes they can be identified as string which gets different color (depends on theme).

In VS Code use `CMD + SHIFT + P` and write `Developer: Inspect TM Scopes`.

**Comment by michaelgmcd** [comment]
For overriding colors in your syntax highlighting (and specifically to give the colors you want) please refer to https://github.com/gandm/language-babel/issues/1
