### ISSUE TITLE
Support for styled-components createGlobalStyle

### ISSUE THREAD

**Issue by curtvict** [michaelgmcd/vscode-language-babel#100]
**Describe the issue**

This extension seems to work great with regular styled components, but doesn't seem apply syntax highlighting for `createGlobalStyle` calls. I'm using the Oceanic Next theme and the screenshot, below, comes from a `.ts` file.

**Screenshot of Current Behavior**

![image](https://user-images.githubusercontent.com/96080054/172427714-2c8678d7-436e-4d8b-a8aa-30b7e45ebb2e.png)

**Sample Code to Reproduce**

You should be able to replicate this easily in a project with:

```
import { createGlobalStyle } from 'styled-components';
...
export const GlobalStyles = createGlobalStyle`
  html {
    box-sizing: border-box;
  }

  *, *:before, *:after {
    box-sizing: inherit;
  }
`;
``

**Comment by michaelgmcd** [comment]
Unfortunately, this plugin is only used for JavaScript files (.js, .jsx). Support for TypeScript is out of scope for several reasons.
