### ISSUE TITLE
Function parameter coloring

### ISSUE THREAD

**Issue by bsvipas** [michaelgmcd/vscode-language-babel#11]
## Before
![image](https://user-images.githubusercontent.com/30043375/31265866-c4641a78-aa79-11e7-8880-4064b22c69e7.png)

## After
![image](https://user-images.githubusercontent.com/30043375/31265899-ecbb33e4-aa79-11e7-9b9d-4be6603c0082.png)

As you can see before it was better, because it know it was `variable.parameter`.

**Comment by michaelgmcd** [comment]
For overriding colors in your syntax highlighting (and specifically to give the colors you want) please refer to https://github.com/gandm/language-babel/issues/1
