### ISSUE TITLE
Tweaks related towards Ocean Next and React

### ISSUE THREAD

**Issue by Mikeysax** [michaelgmcd/vscode-language-babel#12]
I tweaked the curly brackets for React/JSX to match more with Atom.

One problem I had, was with the import statements and variable/arguments. They all fall under `variable.other.readwrite.js` TextMate scope. So, when I tried to color variables and arguments to orange like Atom does, it also makes import statements orange but they are white in Atom. Thought I would bring this up
```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "punctuation.section.embedded", // Braces in JSX
                "settings":{
                    "foreground": "#f99157ff"
                }
            }, 
            {
                "scope": "entity.other.attribute-name", // Classname and props italics
                "settings":{
                    "fontStyle": "italic"
                }
            }
            // {
            //     "scope": "variable.other.readwrite.js", /* variables and arguments not working because coloring imports */
            //     "settings": {
            //         "foreground": "#f99157ff"
            //     }
            // },
            // {
            //     "scope": "variable.other.readwrite.js", // beggining of object variable.
            //     "settings": {
            //         "foreground": "#f99157ff"
            //     }
            // },
        ]
    }
```

Let me know if I need to clarify or if this makes sense.

**Comment by michaelgmcd** [comment]
Interesting. I can take a look at this sometime this week, however at first glance, it seems like more of an issue with the Oceanic Next package.

**Comment by Mikeysax** [comment]
So, am I confused in thinking that the tokens are generated by this babel language package? 
The main issue I think, is in relation to how different variables are tokenized such as arguments in function/defined variables with var const let, and imported variables. They arn't individually selectable so I can't style them individually.

**Comment by michaelgmcd** [comment]
If this is still a problem, please let me know. I'm not too sure what your requirement is.
