### ISSUE TITLE
Support for autocompletion? (styled-components etc.)

### ISSUE THREAD

**Issue by stanleynguyen** [michaelgmcd/vscode-language-babel#13]
I have long been a fan of this package since I used Atom. But recently, I have just migrated to vscode, and found this version of the package. Nevertheless, the autocompletion doesn't feel the same, especially when I use it with styled-components. Is it in your road map to improve the autocompletion? Thank you!

**Comment by thadjbullet** [comment]
https://github.com/Microsoft/typescript-styled-plugin - autocompletion for styled-components in vscode

**Comment by stanleynguyen** [comment]
@thadjbullet Does it work "out-of-the-box"? Looking at the documentation, it seems that I have to include extra project configuration stuffs, of which I feel very unnecessary. The Atom counterpart of this package work without me having to include any extra things in my project configurations

**Comment by thadjbullet** [comment]
Noup. You need to install typescript & typescript-styled-plugin as devDependencies to your project, then select to use installed Typescript version.

**Comment by michaelgmcd** [comment]
Currently, there is no autocompletion provided by this package, as I felt that the autocompletion provided out of the box by VSCode and the typescript-styled-plugin was sufficient. However, I would like to revisit this in the future and put some more thought into it, so I will leave this open for now.

**Comment by alexandernanberg** [comment]
https://github.com/styled-components/vscode-styled-components now works "out-of-the-box" with autocompletion. I've just tested it briefly and it works great so far. Might be nice to have this integrated directly with the plugin, like the Atom plugin does.

**Comment by stanleynguyen** [comment]
@alexandernanberg thank you so much. It works wonders!!
