### ISSUE TITLE
Support syntax highlighting for optional chaining

### ISSUE THREAD

**Issue by gnowth** [michaelgmcd/vscode-language-babel#14]
Hello,

is it possible to support syntax highlighting for the 'optional chaining'.

`const example = obj?.abc?.['def']?.(123, 345);`

**Comment by dhruvdutt** [comment]
Is this supported?

**Comment by TylerBarnes** [comment]
It seems to not be working for me.

**Comment by TylerBarnes** [comment]
I tried deactivating all extensions except for this one as well with the same result.
My filetype is set to Javascript React but I get the same issue on Babel Javascript.
<img width="544" alt="Screen Shot 2019-03-08 at 10 32 59 PM" src="https://user-images.githubusercontent.com/14190743/54067197-29c24780-41f2-11e9-901d-d534313b6c4c.png">

**Comment by TylerBarnes** [comment]
Hmm, it looks like I can set `"javascript.validate.enable": false` to make the optional chaining highlighting go away and it still seems to highlight some errors. Are we supposed to do that when using this extension?

**Comment by michaelgmcd** [comment]
This plugin has nothing to do with the errors you see, only the syntax highlighting.

**Comment by TylerBarnes** [comment]
Makes sense, thanks!
