### ISSUE TITLE
GraphQL fields not yet defined

### ISSUE THREAD

**Issue by lgraziani2712** [michaelgmcd/vscode-language-babel#17]
Hello!

I'm having a visual issue:

![image](https://user-images.githubusercontent.com/15050200/34229782-49ee201a-e5b4-11e7-80ee-11342ab5cfb1.png)

Since `v0.12.0`, GraphQL allows "abstract fields", or not yet defined:

> Update to match Schema definition language latest specification.
> 
> The schema definition language has some slight changes from the original experimental version through the standardization process. New extend forms were added and previously valid forms which omit fields like type Foo {} are now syntax errors and can be replaced with type Foo to indicate that fields are not yet defined.
> 
> From: https://github.com/graphql/graphql-js/releases/tag/v0.12.0

Thank you!

**Comment by michaelgmcd** [comment]
Thanks for using vscode-language-babel! I'm having a little trouble figuring out what your exact issue is. Is it the fact that `anotherSchema` appears to be giving you an error? That would be a different package causing that (eslint maybe?).

**Comment by lgraziani2712** [comment]
Oh! Sorry. I meant the highlightning. It brokes at line 16 because (I think) expects the type Query to have a definition, right?

Since graphql v0.12.0 you can use `type Query` without defining anything.

The `anotherSchema` error was linted by eslint, or flow I think, but is not related to the issue.

Thank you for doing this, BTW 😄

**Comment by michaelgmcd** [comment]
Fixed in latest release
