### ISSUE TITLE
Syntax highlighting breaks when using async + multiple line function params

### ISSUE THREAD

**Issue by lrholmes** [michaelgmcd/vscode-language-babel#19]
To recreate:
```js
const checkPermissions = async (
  ctx,
  nodeId,
  nodeType
) => {
  const userId = getUserId(ctx)
  if (nodeType === 'account') { // correctly highlighted 
  }

  if (nodeType === 'user') { // incorrectly highlighted 
  }
}
```
Image:
<img width="370" alt="screen shot 2018-01-15 at 11 38 02" src="https://user-images.githubusercontent.com/6804978/34940742-a2c67adc-f9e8-11e7-9df4-696884478945.png">

Something to also note is that adding a semi-colon to the first line (`userId`) will break the first if statement's highlighting as well.

Syntax highlighting goes back to normal if removing the `async` keyword or by moving all function params onto one line.

**Comment by michaelgmcd** [comment]
I believe this has been fixed in the latest version. Please update and let me know if it's still an issue.

**Comment by lrholmes** [comment]
Indeed it is fixed - thank you!
