### ISSUE TITLE
component props in red are annoying

### ISSUE THREAD

**Issue by xDae** [michaelgmcd/vscode-language-babel#2]
could be nice if only the `this` keyword is in red a rest in white 

<img width="392" alt="captura de pantalla 2017-06-14 a las 13 20 16" src="https://user-images.githubusercontent.com/6037190/27129966-88d9f00a-5104-11e7-8906-9e0745f75605.png">

**Comment by mgmcdermott** [comment]
Could you send me a slightly larger screenshot? The props should not be all red. I'm thinking that because your lint or some equivalent is failing that the parsing is slightly broken as well.

**Comment by mgmcdermott** [comment]
Also, what theme are you using? It looks like one of the Oceanic Next variants. It's very likely that's causing the issue here.
