### ISSUE TITLE
GLSL tagged template literals

### ISSUE THREAD

**Issue by vxna** [michaelgmcd/vscode-language-babel#20]
I assume setup of [custom tagged template literal grammar extensions](https://github.com/gandm/language-babel/issues/242#issuecomment-256016824) is not possible due lack of the configuration step since is not yet (or never will be) ported.

GLSL [language support](https://marketplace.visualstudio.com/items?itemName=slevesque.shader) exist for vscode and this feature would be pretty much appreciated .

Is there a way to handle this? 

Thanks.

**Comment by michaelgmcd** [comment]
I think this is something reasonable for me to support with vscode's configuration capabilities. Not sure when I'll get to it though. Would love a PR!

**Comment by prayasht** [comment]
How would one get started with adding this feature? I'd love to help but not sure where to start.

All I found is these links, which are for Atom:
- https://github.com/gandm/language-babel/issues/242#issuecomment-256016824
- https://github.com/gandm/language-babel#javascript-tagged-template-literal-grammar-extensions

**Comment by boyswan** [comment]
https://marketplace.visualstudio.com/items?itemName=boyswan.glsl-literal

**Comment by michaelgmcd** [comment]
@prayash Sorry for never getting back to you! Not sure how your message slipped through the cracks. It seems that the package that @boyswan linked works, but custom tagged template literal grammar extensions would probably some similar issues that will inevitably come up in the future.
