### ISSUE TITLE
[Question] Turn strings in JSX White

### ISSUE THREAD

**Issue by timlogemann** [michaelgmcd/vscode-language-babel#22]
I'm used to having strings in elements like `<p>Hello world</p>` in white.
Your extension changes them to the same blue color as my brackets.

I don't expect you to change it, because it's probably a personal preference for you to have them in blue. However I would like to know where I can change this in the extension so that I can fork it and modify it to suit my personal preferences. I don't want to switch to say, Sublime Babel, as I've found this extension better understands when to input the right comments and I really like the different colors for components.

Some images to explain what I mean:
![screen shot 2018-03-23 at 11 14 54](https://user-images.githubusercontent.com/15154878/37824479-09168114-2e8d-11e8-854c-0c615167cc05.png)

![screen shot 2018-03-23 at 11 15 14](https://user-images.githubusercontent.com/15154878/37824480-093022c2-2e8d-11e8-9aeb-0fa2cde6de05.png)

**Comment by michaelgmcd** [comment]
This is based entirely on your chosen theme. I'm currently using "Ayu Mirage" and my JSX strings are white. You can see what the TM scope is by using the command palette (CMD+P) and selecting "Developer: Inspect TM Scopes" with your cursor on the text (see below)
![screen shot 2018-03-23 at 11 17 44 am](https://user-images.githubusercontent.com/8161781/37837542-d90fbec8-2e8b-11e8-83d2-7fc3e3cc6b0f.png)
 Please see https://github.com/gandm/language-babel/issues/1 if you want to manually override your color theme.

**Comment by michaelgmcd** [comment]
Please re-open this if this doesn't work.
