### ISSUE TITLE
Use source.js scope instead of source.js.jsx

### ISSUE THREAD

**Issue by lehni** [michaelgmcd/vscode-language-babel#29]
See https://github.com/vuejs/vetur/issues/825 for an issue I am encountering because vscode-language-babel uses the `source.js.jsx` identifier instead of `source.js` for the JavaScript scope.

What is the reason behind this difference to VSCode's own highlighter?
(See https://github.com/Microsoft/vscode/blob/442e5e202a89c1f8efe642c89c0554cab1f15a9e/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L9)

Could a change to `source.js` be considered to make this extension compatible with Vetur?

**Comment by michaelgmcd** [comment]
In short, this is because this package was originally ported from [the atom equivalent](https://github.com/gandm/language-babel) that uses `source.js.jsx`. I can take a closer look at this sometime this week, but I'm guessing that this would have some unintended side-effects with the react `.jsx` extension.

**Comment by lehni** [comment]
I'm not sure, but we can easily test this. Here's the reason I doubt it may have affects:

```js
	"name": "JavaScript (with React support)",
	"scopeName": "source.js",
```

Emphasis on `(with React support)`. This is from the file linked to above.

**Comment by lehni** [comment]
I've just tested this by manually altering the installed version (`~/.vscode/mgmcdermott.vscode-language-babel-0.0.15`), restarting and then opening a JSX file.

It works without any problems, and Vetur is now also picking it up for syntax highlighting!

<img width="617" alt="screen shot 2018-06-20 at 09 39 41" src="https://user-images.githubusercontent.com/213275/41644305-f90c2842-746d-11e8-892f-6673a70b6ee8.png">

**Comment by michaelgmcd** [comment]
I've pushed out 0.0.16 with a fix for this. From my research of VSCode doing this, they only added `source.js.jsx` to prevent all JavaScript files from being named `JavaScript React`. Hopefully this doesn't have any unintended side-effects, but it seems to be working based on my testing.

**Comment by lehni** [comment]
That’s great! Thanks so much. I’ll test in a moment also.

**Comment by lehni** [comment]
I just tested and it works as expected. Thanks!
