### ISSUE TITLE
Highlighting broken in javascriptreact language based file

### ISSUE THREAD

**Issue by madiodio** [michaelgmcd/vscode-language-babel#30]
I've just noticed that the latest release have broken the syntax highlighting of `javascriptreact` language based files potentially because of [vscode-language-babel/commit/da7b1e2df5f8182814605b11098c32e220bc902d](https://github.com/michaelgmcd/vscode-language-babel/commit/da7b1e2df5f8182814605b11098c32e220bc902d). Am I missing something as to why it was removed?

Thanks for the great work!

**Comment by michaelgmcd** [comment]
That was removed based on my research for https://github.com/michaelgmcd/vscode-language-babel/commit/74258cabed404843cfdd8097e037e64d1b08f392. What specifically is broken?

**Comment by madiodio** [comment]
My bad. But not just syntax highlighting is broken the whole grammar is broken eg. auto-completion specifically in template literals. see the diff below.

(Notice it works with `Babel Javascript` as the language identifier but does not in `javascriptreact)

`Babel Javascript`

![screen shot 2018-06-22 at 00 22 34](https://user-images.githubusercontent.com/15022248/41751932-a3651934-75b3-11e8-94fb-5876aad1ba78.png)

`javascriptreact`
![screen shot 2018-06-22 at 00 23 23](https://user-images.githubusercontent.com/15022248/41751947-bc60f0e8-75b3-11e8-9c0b-91a59c9a2e26.png)

I checked the commit you refered to, but I still don't see why the `javascriptreact` language identifier was removed tough.

**Comment by michaelgmcd** [comment]
I'll revert that change. Thanks for looking into this!

**Comment by michaelgmcd** [comment]
@madiodio I've reverted it and published 0.0.17 with the change. Let me know if you continue to run into issues.

**Comment by madiodio** [comment]
Because of 74258ca we need to map the `javascriptreact`language id. grammars to `source.js` to make it work properly, I've opened #31 for the fix.
