### ISSUE TITLE
Built-in Emmet's Wrap Individual Lines With Abbreviation doesn't work

### ISSUE THREAD

**Issue by skube** [michaelgmcd/vscode-language-babel#32]
When I have the Babel JavaScript extension enabled, the VSCode built-in Emmet: Wrap Individual Lines With Abbreviation doesn't do anything. 

Disabling the extension, Wrap Individual Lines With Abbreviation then works as expected.

Changing the language mode to **JavaScript React** seems to fix the issue.

**Comment by michaelgmcd** [comment]
Please add the following to your vscode settings and let me know if it fixes this:
```
"emmet.includeLanguages": {
    "javascript": "javascriptreact"
  }
```

It seems to work properly on my machine.

**Comment by skube** [comment]
Yup, that seemed to work! Thx.
