### ISSUE TITLE
Causes JS in HTML Syntax Issues

### ISSUE THREAD

**Issue by ahmadawais** [michaelgmcd/vscode-language-babel#33]
Here's what the inline JS issues look like

![image](https://on.ahmda.ws/tIv6/c)

![image](https://on.ahmda.ws/tIdh/c)

**Comment by kayrobin** [comment]
Hi,
I'm having the same issue as well. If I keep the script tags on the same line however, the syntax highlighting begins to work again. It also disables when adjusting tab spacing.
<img width="480" alt="screen shot 2018-08-26 at 1 34 53 am" src="https://user-images.githubusercontent.com/39693538/44625482-93bb7500-a8d0-11e8-8e81-e89d274c2ccf.png">
<img width="751" alt="screen shot 2018-08-26 at 1 42 27 am" src="https://user-images.githubusercontent.com/39693538/44625528-55728580-a8d1-11e8-9991-65f815bbbb34.png">

**Comment by Herohtar** [comment]
I'm getting this problem too.

**Comment by asdfractal** [comment]
This plugin is causing it to think display my html closing tags as if they aren't closing, when there is nothing wrong with the code. when I disable the plugin it goes back to normal display. While only a display error it's off-putting enough that I can't use it with this happening.

![babelerror](https://user-images.githubusercontent.com/24762912/51500346-e8a2df00-1dcd-11e9-92b3-95dd84cec8d3.PNG)

**Comment by michaelgmcd** [comment]
This is an issue with integration with the built-in HTML language mode. I can hopefully take a look this weekend but would appreciate other investigations

**Comment by michaelgmcd** [comment]
This should be fixed in version 0.0.22. Please let me know if it's still an issue.
