### ISSUE TITLE
JSX Tag Closure?

### ISSUE THREAD

**Issue by Siyfion** [michaelgmcd/vscode-language-babel#35]
I'm not sure if I've set something up wrongly, or it's simply an option I'm missing, but I can seem to get my JSX tags to automatically close? (Like in https://github.com/gandm/language-babel#auto-completion-of-jsx-tags-elements-and-attributes) 

Is this by design? Or is there an option to enable it?

**Comment by michaelgmcd** [comment]
Currently, only the syntax highlighting is ported from the atom package. I would like to get around to it eventually, but anything done by the extension code from the atom plugin is not currently supported.

**Comment by Siyfion** [comment]
Ah, no problem. Maybe you could hook into the newly added: https://code.visualstudio.com/updates/v1_26#_jsx-tag-completion ?

**Comment by michaelgmcd** [comment]
Closing as this should now be supported.
