### ISSUE TITLE
function().function()() is highlighted incorrectly

### ISSUE THREAD

**Issue by filiptdz** [michaelgmcd/vscode-language-babel#38]
Expected:
![image](https://user-images.githubusercontent.com/20490694/49801572-b5325680-fd31-11e8-8785-f401d950ec55.png)

Obtained:
![image](https://user-images.githubusercontent.com/20490694/49801604-c713f980-fd31-11e8-9c3c-c0531d4803c9.png)

(It also breaks highlighting in the rest of the file)

**Comment by valscion** [comment]
So the key difference is that the keys are rendered red and not yellow/green?

**Comment by filiptdz** [comment]
@valscion Not really, most highlighting afterwards is broken.

![image](https://user-images.githubusercontent.com/20490694/50353657-11feef80-0530-11e9-91dd-1f0be889228d.png)

In this case, it changes `export` from blue to red, italicises the props and makes the closing JSX bracket red as well. You can see the correct highlighting here:

![image](https://user-images.githubusercontent.com/20490694/50353708-34910880-0530-11e9-9a44-9262cdb187f1.png)
