### ISSUE TITLE
JSX uncommenting unwanted spaces

### ISSUE THREAD

**Issue by cta22** [michaelgmcd/vscode-language-babel#4]
After commenting out JSX like this {/*  <JSX>  */} and uncommenting it back the code is not the same as it was. There is 1 extra space at the begining and 1 at the end of the commented line.

**Comment by michaelgmcd** [comment]
Are you using vscode or vscode-insiders?

**Comment by cta22** [comment]
insiders

**Comment by michaelgmcd** [comment]
Yes, I've seen that issue with insiders and I'm not entirely sure what the cause of it is. The issue doesn't happen in the stable vscode. I'm not familiar with the changes that have been made to insiders to determine what caused this. If I get some time this weekend, I can look into this, but it is not a very high priority for me to support insiders.

**Comment by cta22** [comment]
1.14 was just released so its in stable now :)

**Comment by michaelgmcd** [comment]
I will be looking into this at some point this week.

**Comment by michaelgmcd** [comment]
After further investigation, this happens with _all block comments_ in JavaScript in VSCode in the new version. I have opened an issue about this on the VSCode repo. When that is fixed, this will be as well. https://github.com/Microsoft/vscode/issues/30656
