### ISSUE TITLE
Snippets don't work in jxs tag 

### ISSUE THREAD

**Issue by gespispace** [michaelgmcd/vscode-language-babel#45]
* VSCode Version: 1.31.1
* OS Version: Linux x64 4.15.0-45-generic
* Babel JavaScript: 0.0.20

I want use [ES7 React/Redux/GraphQL/React-Native](https://github.com/dsznajder/vscode-es7-javascript-react-snippets) snippets in jsx tag they don't offered if i turn off the extension offered 
I find comment with the problem in vscode 
[#33723](https://github.com/Microsoft/vscode/issues/33723#issuecomment-328902806)

**Comment by michaelgmcd** [comment]
This is a little unclear. The comment you've linked refers to other Babel projects. Are you saying it happens for this one as well?

**Comment by gespispace** [comment]
Yes, if i turn on [this](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) extensions my snippet don't work. And the comment say that work with other Babel projects.

**Comment by michaelgmcd** [comment]
Does [this solution](https://stackoverflow.com/questions/42022456/vscode-chooses-unusual-option-for-autocomplete/42107910#42107910) work for you? I was able to install the extension you listed and get it working with `"editor.snippetSuggestions": "top"` set in my settings.

**Comment by gespispace** [comment]
Sorry for the late reply.

Yes, this solution work. But i want see Snippets in suggests.

**Comment by phoydar** [comment]
I'm also experiencing an issue with not seeing common JS snippets inside of JSX. the default js `log` snippet trigger no longer works and doesn't show up in the Vscode intellisense list when I enable the plugin.

Extension disabled. Outside JSX (Works as expected)
![image](https://user-images.githubusercontent.com/31257623/63098049-f8d40480-bf3f-11e9-9afb-59bb8f4a0dbe.png)
 
Extension disabled. Inside JSX (Works as expected)
![image](https://user-images.githubusercontent.com/31257623/63098073-07222080-bf40-11e9-9f09-1b882fc11033.png)

Extension enabled. Outside JSX (Works as expected)
![image](https://user-images.githubusercontent.com/31257623/63098106-1ef9a480-bf40-11e9-92bb-a24656cc4470.png)

Extension enabled. Inside JSX (Does not work as expected)
![image](https://user-images.githubusercontent.com/31257623/63098113-2620b280-bf40-11e9-9cdc-0388f71105d5.png)

**Comment by exocode** [comment]
I also found out, that at some places the snippets are working and some are not:
See here, very curious.
I hope this video will help:

![2020-02-13 12 13 56](https://user-images.githubusercontent.com/1597621/74429598-9494ed80-4e5b-11ea-8b14-0beb75039e19.gif)

**Comment by michaelgmcd** [comment]
Thanks for the in depth video @exocode. I'll take a look at this when I can.

**Comment by exocode** [comment]
> Thanks for the in depth video @exocode. I'll take a look at this when I can.

Good luck :-)

**Comment by michaelgmcd** [comment]
@exocode The issue here is that VSCode Language Babel adds two new languages for JSX and JSX Attributes (for several reasons). These snippets need to be applied for those languages as well to be available in JSX. I've created a PR to the repo you referenced to add support. Unfortunately, this will need to be done for any snippet projects. Could be some of your chances to contribute to open source!
