### ISSUE TITLE
Null Coalescing Operator 

### ISSUE THREAD

**Issue by tparikka** [michaelgmcd/vscode-language-babel#48]
I'm new-ish to TypeScript and hoping to use this extension to utilize TC39 proposals in VS Code. However, with the extension installed, syntax highlighting still shows an issue:

![image](https://user-images.githubusercontent.com/7715790/55049412-06810000-501a-11e9-9179-b05f9b6145bb.png)

I tried changing the language mode to Babel Javascript but it didn't make a difference - perhaps because I'm in TS? I couldn't find any info in the existing issues or readme that would tell me what I might be doing wrong. My extensions are at:

https://gist.github.com/tparikka/1ce22cf43a5922999cf81d7e8d2b9510

My installed version is:
Version: 1.32.3 (user setup)
OS: Windows_NT x64 10.0.17763

This is my babelrc:

```
{
	"presets": [
			"@babel/typescript"
	],
	"plugins": [
			"@babel/proposal-class-properties",
			"@babel/proposal-object-rest-spread",
			"@babel/plugin-proposal-optional-chaining",
			"@babel/plugin-proposal-nullish-coalescing-operator"
	]
}
```

Thank you for any help you can provide!

**Comment by michaelgmcd** [comment]
Yes, unfortunately there's not much I can do here. I can't really say what the expected behavior should be of trying to use this project with TypeScript files. I would open this question directly to the vscode repository.

**Comment by tparikka** [comment]
Thank you! I appreciate the response!
