### ISSUE TITLE
Tree Sitter support?

### ISSUE THREAD

**Issue by kurtextrem** [michaelgmcd/vscode-language-babel#49]
VS Code now has a Tree Sitter extension: https://github.com/georgewfraser/vscode-tree-sitter Might be worth switching to that syntax

**Comment by michaelgmcd** [comment]
I'm not too familiar with Tree Sitter. What would be the work involved outside of [what is on their README](https://github.com/georgewfraser/vscode-tree-sitter#adding-a-new-language) (which would be a decent amount of work)? What would be the benefits? More accurate highlighting?
