### ISSUE TITLE
Comments in Tagged Template Literals

### ISSUE THREAD

**Issue by cusxio** [michaelgmcd/vscode-language-babel#5]
It seems that the commenting of tagged template literals behaves different from Atom's `language-babel` package?

### Atom

![kapture 2017-08-07 at 8 57 29](https://user-images.githubusercontent.com/6487613/29008780-011a67ce-7b4f-11e7-95a9-d7330ad07af3.gif)

### VSCode

![kapture 2017-08-07 at 8 56 30](https://user-images.githubusercontent.com/6487613/29008782-03e6e00e-7b4f-11e7-991d-73c141ec59c7.gif)

**Comment by michaelgmcd** [comment]
Yes, this was difficult to port due to the differences in how Atom and VSCode handle embedded languages and commenting. I have looked a little bit into this but haven't had luck just yet. Hoping to work on it a little bit more this week.

**Comment by michaelgmcd** [comment]
Put some more effort into this last night, but no luck yet! Still working on this when I can.

**Comment by michaelgmcd** [comment]
This should be fixed in version 0.0.10. Let me know if you have issues with this!
