### ISSUE TITLE
keywords ' in ' is highlighting incorrectly

### ISSUE THREAD

**Issue by cyphernull** [michaelgmcd/vscode-language-babel#54]
![image](https://user-images.githubusercontent.com/23122353/62105706-b242a100-b2d5-11e9-9deb-2adda1f6b37d.png)

**Comment by michaelgmcd** [comment]
"Incorrectly" is a little vague. VSCode styles this differently in TypeScript as well. The TM Scope is `keyword.operator.in.js` so I'm sure you could style it differently in your theme.
