### ISSUE TITLE
Syntax highlighting option doesn't appear in list

### ISSUE THREAD

**Issue by karmeleon** [michaelgmcd/vscode-language-babel#59]
When I open any file and open the syntax highlighting menu, I don't see "Babel JavaScript". It used to work, but at some point it stopped appearing. I don't see anything in the inspector that seems relevant. I've tried deleting all my extensions and settings and only installing this extension, but it didn't help. Let me know if there are any logs or anything that might help!

VSCode 1.40.1
Windows 10 x64 Enterprise 1903

**Comment by ThaJay** [comment]
The setting used for .js files (the ones that were configures to use this) have also reverted to just JavaScript.

**Comment by mdrx-io** [comment]
Anyone know offhand which was the last version of VSCode to have it working?

**Comment by karmeleon** [comment]
Ah I figured it out! I'm using VSCode Remote SSH, and when I'm connected the extensions menu shows that the Babel JavaScript extension is "Enabled on 'SSH: [my ssh server name]' and disabled locally.". If I open a new, local VSCode window and open a new file, the extension is installed and I can successfully enable the Babel JS syntax highlighting.

The fix is to tag this extension's `package.json` with `extensionKind: ["ui"]` as outlined in the [VSC remote extension docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). As a quick local fix until a new version can be released, you can force the extension to be `ui` installed by copypasting this into your `settings.json`:

```json
"remote.extensionKind": {
    "mgmcdermott.vscode-language-babel": ["ui"]
},
```

Reload the window and Babel JavaScript will appear as a syntax highlighting option, with the extension showing up as installed locally.

**Comment by ThaJay** [comment]
@karmeleon I think this issue has been solved and you are posting about a different issue.

**Comment by michaelgmcd** [comment]
Cleaning up some issues. It seems like this is fixed. Please comment here if that is not the case.
