### ISSUE TITLE
Emmet is not working with this VSCode extension

### ISSUE THREAD

**Issue by jeud** [michaelgmcd/vscode-language-babel#6]
Dear all

I used to use `Babel ES6/ES7` extension (`dzannotti.vscode-babel-coloring`), this extension works fine with emmet abbreviation

Please guide how to setup this `Babel JavaScript` extension to work with emmet abbreviation

My VSCode setting

```json
{
    "emmet.showAbbreviationSuggestions": true,
    "emmet.showExpandedAbbreviation": "always",
    "emmet.syntaxProfiles": {
        "javascript": "html",
        "html": {
            "self_closing_tag": false,
            "tag_case": "lower"
        },
        "xml": {}
    },
    "files.associations": {
        "*.jsx": "javascriptreact",
        "*.html": "html"
    }
}
```

Thanks all

**Comment by michaelgmcd** [comment]
Hey, thanks for using vscode-language-babel! Are you trying to expand with tab? I would first ask that you try using the command palette (Cmd+Shift+P) and click "Emmet: Expand Abbreviation" to toggle the abbreviation. If that doesn't work, I can help you debug further.

If you are trying to expand the abbreviation with Tab, then make sure you have `emmet.triggerExpansionOnTab` set to `true` in your settings. I got this working on my machine by using all of the default settings except for `emmet.triggerExpansionOnTab: true`.

**Comment by michaelgmcd** [comment]
I would suggest trying all of the suggestions in [this issue](https://github.com/Microsoft/vscode/issues/4962) and then let me know if you're still having trouble.

**Comment by jeud** [comment]
@michaelgmcd 

thanks for such a great extension, at this moment `"emmet.triggerExpansionOnTab": true` is working great for me

**Comment by ArmorDarks** [comment]
Did someone managed to make it work?

I've tried

```
    "emmet.includeLanguages": {
        "javascript": "jsx"
    },
    "emmet.triggerExpansionOnTab": true,
```

but I'm getting following error when trying to expand abbreviation: https://i.imgur.com/03GPJvV.png
