### ISSUE TITLE
Stupid question: how to enable it after installing it?

### ISSUE THREAD

**Issue by mwdpb** [michaelgmcd/vscode-language-babel#68]
More specifically, how to disable VSCode's built-in JS syntax highlighting and enable this plugin?  Or is it simply co-existent with VSCode built-in JS highlighting?  Thanks.

**Comment by michaelgmcd** [comment]
No worries! It should overwrite the default built-in syntax highlighting. Try reloading or re-opening VSCode and see if it shows up.

**Comment by mwdpb** [comment]
Thanks for the quick response!  Any way to indicate it is being deployed?  I've restarted VSCode couple of times, but the syntax highlighting looks still just like the built-in JS synatax highlighting.
