### ISSUE TITLE
Does it support code completion for styled-components?

### ISSUE THREAD

**Issue by SidKwok** [michaelgmcd/vscode-language-babel#7]
It's annoying when you have to type all the letters. `language-babel` seems to support such feature.

**Comment by michaelgmcd** [comment]
This package has less of a scope (for now) as `language-babel`. It does not support separate code completion like the atom version. I can look more into this in the near future.

**Comment by SidKwok** [comment]
Have you tried [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin)? I think this library can solve this issue perfectly.
