### ISSUE TITLE
CSS comment doesnt work

### ISSUE THREAD

**Issue by artalar** [michaelgmcd/vscode-language-babel#70]
CSS comment doesn't work for highlighting css in template literals :

![image](https://user-images.githubusercontent.com/27290320/83383763-77763180-a3ee-11ea-95a9-8143abc57b32.png)

Example

```ts
const styles = /* CSS */`
  tag {
    display: none;
  }
`
```

**Comment by michaelgmcd** [comment]
Hey @artalar, thanks for using vscode-language-babel! In your screenshot, it looks like you're using TypeScript and not JavaScript. You'll know if this plugin is active when it says "Babel JavaScript" in the bottom right-hand corner (currently says "TypeScript React"). Please reopen this issue if it persists in JS.
