### ISSUE TITLE
Syntax highlighting breaks after HTML <script> tag

### ISSUE THREAD

**Issue by Flandre-X** [michaelgmcd/vscode-language-babel#71]
**Describe the issue**
If a line of JavaScript within a `script` tag in HTML doesn't end in a semicolon, it _sometimes_ breaks the syntax highlighting for the rest of the file.

**Screenshot of Current Behavior**
![image](https://user-images.githubusercontent.com/38332081/84748101-cc34b300-af7d-11ea-9698-16b30033d9ee.png)
![image](https://user-images.githubusercontent.com/38332081/84748158-deaeec80-af7d-11ea-9877-99ffe567a9c3.png)
![image](https://user-images.githubusercontent.com/38332081/84748313-13bb3f00-af7e-11ea-8d42-360377da7613.png)

**Sample Code to Reproduce**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <script>
    require("source-map-support/source-map-support.js").install()
  </script></head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

**Comment by sevenseacat** [comment]
why was this closed? I'm still seeing it as a problem :(

**Comment by Flandre-X** [comment]
Oops, I don't remember why I closed it.

**Comment by michaelgmcd** [comment]
Only looked into this briefly, but adding a semi-colon after `install()` fixes the issue. I'll continue to investigate when I can.

**Comment by michaelgmcd** [comment]
In short, this is a pretty difficult issue to debug. I believe it was introduced in https://github.com/michaelgmcd/vscode-language-babel/pull/56. Handling flow-type arguments has added quite a bit of complexity to function and method calls.

**Comment by michaelgmcd** [comment]
Try this out in 0.0.35 and let me know if this still exists.
