### ISSUE TITLE
Syntax highlighting breaks after using styled-components css helper in TypeScript

### ISSUE THREAD

**Issue by Flandre-X** [michaelgmcd/vscode-language-babel#73]
**Screenshot of Current Behavior**

![image](https://user-images.githubusercontent.com/38332081/86837447-8e9ae580-c064-11ea-9485-5dc591308a66.png)

It works when we remove the generic tag:

![image](https://user-images.githubusercontent.com/38332081/86837537-a8d4c380-c064-11ea-9d49-6b7410c8c2ad.png)

Interestingly, it also works with styled.(tag)&lt;type&gt;:

![image](https://user-images.githubusercontent.com/38332081/86836786-a160ea80-c063-11ea-94f2-42ac45c1960e.png)

**Sample Code to Reproduce**
```javascript
const StyledButtonPlay = css<ButtonProps>`
  width: 50px;
  height: 50px;
  border-width: 50px;

  &:hover {
    border-left-color: white;
    cursor: pointer;
  }
`;

const StyledButtonPause = css<ButtonProps>`
  &:hover {
    border-color: white;
  }
`;

export const StyledButton = styled.button<ButtonProps>`
  box-sizing: border-box;
  background-color: transparent;
  border-style: solid;
  border-color: transparent transparent transparent #282a2d;

  ${(props) => (
    props.paused
      ? StyledButtonPlay
      : StyledButtonPause
  )}
`;
```

(Property interpolations were used in the original code for StyledButtonPlay, but they were removed here for brevity. The generic tag is required for the original code to work in TypeScript.)

**Comment by michaelgmcd** [comment]
Unfortunately @Flandre-X, the syntax highlighting provided by this plugin is only available for JavaScript (.js, .jsx) files. There are several reasons for not supporting .ts/.tsx. The first that come to mind are:
- It would be unexpected from a package with JavaScript in the name
- TypeScript is a very active language. The VSCode team does a great job of keeping the syntax highlighting up to date. Keeping parity in this package would be very difficult.

I would give [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) a whirl if you haven't already.
