### ISSUE TITLE
Extension overwrites color from Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by j4cky11** [michaelgmcd/vscode-language-babel#76]
**Describe the issue**
After installing, it's removes all colors given by BPC2, from bracket and parenthesis symbols.
Before: ![before](https://i.imgur.com/nbL9D8D.png)
After:  ![before](https://i.imgur.com/fsl5koH.png)

**Comment by michaelgmcd** [comment]
Could you send me the list of your plugins? It works fine on my machine.

**Comment by j4cky11** [comment]
https://gist.github.com/j4cky11/90a4e222b6999788d5bfd4da243478f2

**Comment by michaelgmcd** [comment]
Thanks. Could you try the "Atom One Dark" theme and see if the issue persists?

**Comment by j4cky11** [comment]
Same thing.

**Comment by michaelgmcd** [comment]
Hmm. Very weird. Glad the issue's resolved!
