### ISSUE TITLE
Hello, author! Can you provide the code font

### ISSUE THREAD

**Issue by FrontTutu** [michaelgmcd/vscode-language-babel#88]
Hello, author! What is the font of this picture? This code font is so beautiful!

![1622011516344](https://user-images.githubusercontent.com/44667878/119616950-d456cd00-be33-11eb-9296-2a5f42c8e956.jpg)

**Comment by michaelgmcd** [comment]
I switch fonts quite a bit, but I believe this one is Operator Mono!

**Comment by FrontTutu** [comment]
> 
That is great! Thank the author
