### ISSUE TITLE
Update the changelog

### ISSUE THREAD

**Issue by futagoza** [michaelgmcd/vscode-language-babel#9]
I know I can come here and check what has changed by looking at the [commits](https://github.com/michaelgmcd/vscode-language-babel/commits/master), but it would be nice if you can update the changelog before publishing the updated extension, it's so much simpler just looking on the extensions changelog tab 😄

**Comment by michaelgmcd** [comment]
Yes, I agree! Was in a hurry to push a fix for the jsconfig issue so I left out the changelog change.

**Comment by michaelgmcd** [comment]
Fixed in 4345b71687ba847ddce746af49c11935c56dd09c
