### ISSUE TITLE
Breaks highlighting HTML when a script tag omits semicolons

### ISSUE THREAD

**Issue by kentcdodds** [michaelgmcd/vscode-language-babel#91]
All the info you need is in this issue: https://github.com/microsoft/vscode/issues/121577

I'll just copy over the contents of [this comment](https://github.com/microsoft/vscode/issues/121577#issuecomment-901190738):

![image](https://user-images.githubusercontent.com/1500684/129922122-ba2cd7fe-3fcb-4cb6-a2c7-4fef9e523832.png)

Looks like it's exactly the same as my other screenshot.

What I find interesting is when I put my cursor on the closing `</script>` html tag or even the `</html>`, it incorrectly identifies language as "JavaScript"

![image](https://user-images.githubusercontent.com/1500684/129922483-2998bae0-4203-40cb-84ed-0508471a0981.png)

However, if I add a semicolon, it correctly identifies it as HTML:

![image](https://user-images.githubusercontent.com/1500684/129922505-024934a2-d12e-4758-9999-ad9e964b0179.png)

I would expect it to be able to identify it as the correct language regardless of the presence of the semicolon.

Once I switched off this plugin I no longer had these problems:

![image](https://user-images.githubusercontent.com/1500684/130366834-e0f4fbd9-2b8c-4c84-92d7-6fe13261946c.png)

**Comment by michaelgmcd** [comment]
Hey Kent! Taking a look at this now. For some context, this issue (and ones like it) tend to get a bit hairy because this package is an "all-in-one" solution for what VSCode splits into "javascript" and "javascriptreact".

**Comment by michaelgmcd** [comment]
As an example, the code in [test.html](https://github.com/michaelgmcd/vscode-language-babel/blob/master/test.html) works without semicolons, but the snippet from your issue does not. Syntax highlighting is fun!

```
<html>
  <title>Title</title>
  <lang>en</lang>
  <body></body>
  <script>
    const rootElement = document.createElement('div')
    rootElement.id = 'root'
    document.body.append(rootElement)

    const helloWorldElement = document.createElement('div')
    helloWorldElement.textContent = 'Hello World'
    rootElement.append(helloWorldElement)
  </script>
</html>
```

**Comment by michaelgmcd** [comment]
The following simple cases seem to break the highlighting. Putting a pin in this for now, so using this thread for note-taking:
```html
<script>
  let foo
</script>
```
```html
<script>
  foo.bar()
</script>
```

Like I mentioned, debugging this is pretty difficult, but narrowing it down to these cases is a start. There's an issue with a regex somewhere, it's just a matter of tracking it down.

**Comment by michaelgmcd** [comment]
Try out 0.0.35 Kent. The changes I made _may_ have some side effects, but it looks good in my testing.

**Comment by kentcdodds** [comment]
Thanks! After disabling this extension for a while I actually realized I'm not sure I need this extension anymore 😅 But if I decide I do I'll try this out and let you know. Thanks Michael!
