### ISSUE TITLE
Enable vscode-language-babel to work with VS Code on the Web

### ISSUE THREAD

**Issue by isidorn** [michaelgmcd/vscode-language-babel#97]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure vscode-language-babel can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

If this is not possible I noticed that you also contribute a `grammars`, so it would be cool if you could use `when` context keys to disable all other non `grammar` contributions when in web, such that `grammars` still work in the web.

Please let us know if you have questions or feedback on enabling your extension for the web - our team would love to learn from your experiences and collaborate. Thank you!

**Comment by michaelgmcd** [comment]
This should be supported in 0.036

**Comment by isidorn** [comment]
@michaelgmcd awesome, thanks a lot 👏
